# Generated by Django 5.1.3 on 2024-12-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursosApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incripcion',
            new_name='Inscripcion',
        ),
    ]
