# Generated by Django 5.1.3 on 2024-12-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursosApp', '0002_rename_incripcion_inscripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name': 'Inscripcion', 'verbose_name_plural': 'Inscripciones'},
        ),
    ]
